dpid: 2
hard_timeout: 0
idle_timeout: 900
table_id: 0
priority: 47000
details:
    serverIPtoHost:
        cookie_base: 1
        matches:
            in_port: 1
            eth_type: 0x0800 #IPv4 traffic only at the moment
            ipv4_src: serverIP
        actions:
            out_port: 5
 
    hostIPtoServer:
        cookie_base: 3000
        matches:
            in_port: 2
            eth_type: 0x0800 #IPv4 traffic only at the moment
            ipv4_dst: serverIP
        actions:
            out_port: 5
